---
title: "1st line administration date"
author: "Yuki Saito"
date: "2024-03-07"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(lubridate)
```

```{r source}
source("../../R/utils.R")
```

```{r read in merged data, warning=FALSE, message=FALSE}
# read in merged data
merged_data <- read_csv("result/table/merged/merged_patient_data6.csv", na = "")
merged_data
```

```{r preparation}
# list up organ names
organ_names <- list.files("../../../sh_c-cat_analysis/data/ccat/ver20240621/F1CDx/",
                          full.names = FALSE)
organ_names[1:3]

# colnames reference
case_colnames_df <- read_xlsx("../../ref/colnames_ver202406.xlsx", "case") %>% 
  filter(Pre_treatment_columns == "TRUE")
head(case_colnames_df)

case_cols <- case_colnames_df
case_cols["coltypes"][case_cols["coltypes"] == "character"] <- "c"
case_cols["coltypes"][case_cols["coltypes"] == "numeric"] <- "n"
case_cols["coltypes"][case_cols["coltypes"] == "logical"] <- "l"
case_cols["coltypes"][case_cols["coltypes"] == "date"] <- "D"
case_cols_collapsed <- paste(case_cols$coltypes, collapse = "")
```

```{r analysis, warning=FALSE, message=FALSE}
pre_treatment_data <- list()
for (organ in organ_names){
  # read in post-treatment data
  organ_pre_treatment_data <- read_csv(paste0("result/table/prep/case/", organ, "/pre_treatment_data.csv"),
                                       col_types = case_cols_collapsed)
  pre_treatment_data[[organ]] <- organ_pre_treatment_data
}
pre_treatment_data <- bind_rows(pre_treatment_data)
```

```{r first chemo date, message=FALSE, warning=FALSE}
preEP_treatment_data_summary <- pre_treatment_data %>%
  group_by(Tumor_Sample_Barcode) %>% 
  summarize(min_PreEP_regimen_startdate = min(PreEP_regimen_startdate, na.rm = TRUE)) %>% 
  ungroup()
preEP_treatment_data_summary
```

```{r save}
merged_data <- merged_data %>% 
  left_join(preEP_treatment_data_summary, by = "Tumor_Sample_Barcode")
merged_data %>% 
  write_excel_csv("result/table/merged/merged_patient_data7.csv", na = "")
```

```{r sessioninfo}
sessionInfo()
```
