---
title: "alteration"
author: "Yuki Saito"
date: "2025-02-04"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(lubridate)
```

```{r source}
source("../../R/utils.R")
```

```{r read in merged data, warning=FALSE, message=FALSE}
# read in merged data
merged_data <- read_csv("result/table/merged/merged_patient_data8.csv", na = "")
merged_data

CODE_data <- merged_data %>% 
  select(Tumor_Sample_Barcode,
         Oncotree_CODE,
         Oncotree_CODE_name,
         ONCOTREE_Level1,
         ONCOTREE_Level1_name,
         Oncotree_CODE_Final_wide,
         Oncotree_CODE_Final_narrow)
CODE_data
```

```{r preparation}
# list up organ names
organ_names <- list.files("../../../sh_c-cat_analysis/data/ccat/ver20240621/F1CDx/",
                          full.names = FALSE)
organ_names[1:3]
```

```{r numbers, warning=FALSE, message=FALSE}
# colnames reference
report_colnames_df <- read_xlsx("../../ref/colnames_ver202406.xlsx", "report") %>% 
  filter(Number_columns == "TRUE")
head(report_colnames_df)

report_cols <- report_colnames_df
report_cols["coltypes"][report_cols["coltypes"] == "character"] <- "c"
report_cols["coltypes"][report_cols["coltypes"] == "numeric"] <- "n"
report_cols["coltypes"][report_cols["coltypes"] == "logical"] <- "l"
report_cols["coltypes"][report_cols["coltypes"] == "date"] <- "D"
report_cols_collapsed <- paste(report_cols$coltypes, collapse = "")

number_data <- list()
for (organ in organ_names){
  # read in post-treatment data
  organ_number_data <- read_csv(paste0("result/table/prep/report/", organ, "/number_data.csv"),
                                       col_types = report_cols_collapsed)
  number_data[[organ]] <- organ_number_data
}
number_data <- bind_rows(number_data)
```

```{r numbers2, warning=FALSE, message=FALSE}
# SNV
SNV_list <- list()
for (organ in organ_names){
  tmp_SNV_data <- read_csv(paste0("result/table/prep/report/", organ, "/small_scale_variant_data.csv"))
  SNV_list[[organ]] <- tmp_SNV_data
}
SNV_data <- bind_rows(SNV_list) %>% 
  left_join2(CODE_data)

# CNV
CNV_list <- list()
for (organ in organ_names){
  tmp_CNV_data <- read_csv(paste0("result/table/prep/report/", organ, "/CNV_data.csv"))
  CNV_list[[organ]] <- tmp_CNV_data
}
CNV_data <- bind_rows(CNV_list) %>% 
  left_join2(CODE_data)

# Rearrangement
Rearrangement_list <- list()
for (organ in organ_names){
  tmp_Rearrangement_data <- read_csv(paste0("result/table/prep/report/", organ, "/Rearrangement_data.csv"))
  Rearrangement_list[[organ]] <- tmp_Rearrangement_data
}
Rearrangement_data <- bind_rows(Rearrangement_list) %>% 
  left_join2(CODE_data)
```

```{r save}
SNV_data %>% 
  write_excel_csv("result/table/merged/merged_SNV_data.csv")
CNV_data %>%
  write_excel_csv("result/table/merged/merged_CNV_data.csv")
Rearrangement_data %>%
  write_excel_csv("result/table/merged/merged_Rearrangement_data.csv")
```

```{r sessioninfo}
sessionInfo()
```
