---
title: "prognosis by treatment strategy"
author: "Yuki Saito"
date: "2024-09-24"
output: html_document
---

- R markdown script to evaluate prognosis by treatment strategies.

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r library}
library(tidyverse)
library(dplyr)
library(readxl)
library(lubridate)
library(ggsurvfit)
library(gtsummary)
library(survival)
library(survminer)
```

```{r source}
source("../../R/utils.R")
source("../../R/cancer_type_order_v4.R")
```

```{r read in merged data, warning=FALSE, message=FALSE}
# read in merged data
merged_data <- read_csv("result/table/merged/merged_patient_data10.csv", na = "") %>% 
  mutate(Age_category = case_when(Age < 65 ~ "<65",
                                  Age >= 65 & Age < 75 ~ "65-74",
                                  Age >= 75 ~ ">=75")) %>%
  mutate(Age_category = factor(Age_category, levels = c("<65", "65-74", ">=75"))) %>% 
  mutate(Sex_name = if_else(Sex == 9, NA_character_, Sex_name))
merged_data

merged_data <- merged_data %>% 
  filter(Pre_regimen_info_existence == "Yes")
```

```{r function}
ggColorHue <- function(n, l=65) {
  hues <- seq(15, 375, length=n+1)
  hcl(h=hues, l=l, c=100)[1:n]
}
```

```{r pan-cancer, warning=FALSE}
# check
merged_data %>% 
  count(PostEP_treatment_policy_name_estimated_rough, PostEP_treatment_policy_name_estimated_detail)

merged_data$PostEP_treatment_policy_name_estimated_detail <- factor(
  merged_data$PostEP_treatment_policy_name_estimated_detail,
  levels = c("Chemotherapy", "BSC", "Clinical_trial", "Other_off_label")
)

count <- survdiff(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail, data = merged_data)
print(count)
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = merged_data))
print(stat)
stat$coefficients

stat_df <- tibble(Oncotree_CODE_Final_wide = "PanCan",
                  chemo_num = count$n[["PostEP_treatment_policy_name_estimated_detail=Chemotherapy"]],
                  
                  # clinical trial
                  clinical_trial_num = count$n[["PostEP_treatment_policy_name_estimated_detail=Clinical_trial"]],
                  clinical_trial_hazard_ratio = stat$conf.int["PostEP_treatment_policy_name_estimated_detailClinical_trial","exp(coef)"],
                  clinical_trial_lower95 = stat$conf.int["PostEP_treatment_policy_name_estimated_detailClinical_trial","lower .95"],
                  clinical_trial_higher95 = stat$conf.int["PostEP_treatment_policy_name_estimated_detailClinical_trial","upper .95"],
                  clinical_trial_wald_p = stat$coefficients["PostEP_treatment_policy_name_estimated_detailClinical_trial","Pr(>|z|)"],
                  
                  # other off label
                  other_off_label_num = count$n[["PostEP_treatment_policy_name_estimated_detail=Other_off_label"]],
                  other_off_label_hazard_ratio = stat$conf.int["PostEP_treatment_policy_name_estimated_detailOther_off_label","exp(coef)"],
                  other_off_label_lower95 = stat$conf.int["PostEP_treatment_policy_name_estimated_detailOther_off_label","lower .95"],
                  other_off_label_higher95 = stat$conf.int["PostEP_treatment_policy_name_estimated_detailOther_off_label","upper .95"],
                  other_off_label_wald_p = stat$coefficients["PostEP_treatment_policy_name_estimated_detailOther_off_label","Pr(>|z|)"],
                  
                  # BSC
                  BSC_num = count$n[["PostEP_treatment_policy_name_estimated_detail=BSC"]],
                  BSC_hazard_ratio = stat$conf.int["PostEP_treatment_policy_name_estimated_detailBSC","exp(coef)"],
                  BSC_lower95 = stat$conf.int["PostEP_treatment_policy_name_estimated_detailBSC","lower .95"],
                  BSC_higher95 = stat$conf.int["PostEP_treatment_policy_name_estimated_detailBSC","upper .95"],
                  BSC_wald_p = stat$coefficients["PostEP_treatment_policy_name_estimated_detailBSC","Pr(>|z|)"]
                  )

# Explicitly reorder the factor levels
merged_data$PostEP_treatment_policy_name_estimated_detail <- factor(
  merged_data$PostEP_treatment_policy_name_estimated_detail,
  levels = c("BSC", "Chemotherapy", "Clinical_trial", "Other_off_label")
)
# Create the plot
fig <- ggsurvfit(survfit2(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail, data = merged_data), size = 1.5) +
  #add_censor_mark(size = 0.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 4),
                  ylim = c(0, 1)) +
  labs(x = "Years",
       y = "Probability of Overall Survival") +
  ggtitle("PanCan") +
  scale_color_manual(
    name = "Post-CGP treatment policy",
    values = c(
      "BSC" = "gray60",
      "Chemotherapy" = ggColorHue(6)[3],
      "Clinical_trial" = ggColorHue(6)[1],
      "Other_off_label" = ggColorHue(6)[5]
    )) +
  cowplot::theme_cowplot()
print(fig)

ggsave("result/pdf/analysis/overall_prognosis/OS_by_treatment_policy.pdf", width = 8, fig)
ggsave("result/pdf/analysis/overall_prognosis/OS_by_treatment_policy_no_legend.pdf", width = 8, fig + theme(legend.position = "none"))
ggsave("result/pdf/analysis/overall_prognosis/OS_by_treatment_policy_risktable.pdf", width = 8, fig + add_risktable() + add_risktable_strata_symbol())
```

```{r by evidence level}
merged_data$PostEP_treatment_policy_name_estimated_detail <- factor(
  merged_data$PostEP_treatment_policy_name_estimated_detail,
  levels = c("Chemotherapy", "Clinical_trial", "Other_off_label", "BSC")
)

# Evidence A (approved)
tmp_data <- merged_data %>% 
  filter(Highest_evidence_level2 == "Evidence_A(approved)")

count <- survdiff(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data)
print(count)
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = tmp_data))
print(stat)
stat$coefficients

fig <- ggsurvfit(survfit2(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data), size = 1.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 4),
                  ylim = c(0, 1)) +
  labs(x = "Years",
       y = "Probability of Overall Survival") +
  ggtitle("Evidence_A(approved)") +
  scale_color_manual(
    name = "Post-CGP treatment policy",
    values = c(
      "BSC" = "gray60",
      "Chemotherapy" = ggColorHue(6)[3],
      "Clinical_trial" = ggColorHue(6)[1],
      "Other_off_label" = ggColorHue(6)[5]
    )) +
  cowplot::theme_cowplot()
print(fig)

# Evidence A (unapproved)
tmp_data <- merged_data %>% 
  filter(Highest_evidence_level2 == "Evidence_A(unapproved)")

count <- survdiff(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data)
print(count)
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = tmp_data))
print(stat)
stat$coefficients

fig <- ggsurvfit(survfit2(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data), size = 1.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 4),
                  ylim = c(0, 1)) +
  labs(x = "Years",
       y = "Probability of Overall Survival") +
  ggtitle("Evidence_A(unapproved)") +
  scale_color_manual(
    name = "Post-CGP treatment policy",
    values = c(
      "BSC" = "gray60",
      "Chemotherapy" = ggColorHue(6)[3],
      "Clinical_trial" = ggColorHue(6)[1],
      "Other_off_label" = ggColorHue(6)[5]
    )) +
  cowplot::theme_cowplot()
print(fig)

# Evidence B
tmp_data <- merged_data %>% 
  filter(Highest_evidence_level2 == "Evidence_B")

count <- survdiff(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data)
print(count)
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = tmp_data))
print(stat)
stat$coefficients

fig <- ggsurvfit(survfit2(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data), size = 1.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 4),
                  ylim = c(0, 1)) +
  labs(x = "Years",
       y = "Probability of Overall Survival") +
  ggtitle("Evidence_B") +
  scale_color_manual(
    name = "Post-CGP treatment policy",
    values = c(
      "BSC" = "gray60",
      "Chemotherapy" = ggColorHue(6)[3],
      "Clinical_trial" = ggColorHue(6)[1],
      "Other_off_label" = ggColorHue(6)[5]
    )) +
  cowplot::theme_cowplot()
print(fig)

# Evidence C
tmp_data <- merged_data %>% 
  filter(Highest_evidence_level2 == "Evidence_C")

count <- survdiff(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data)
print(count)
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = tmp_data))
print(stat)
stat$coefficients

fig <- ggsurvfit(survfit2(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data), size = 1.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 4),
                  ylim = c(0, 1)) +
  labs(x = "Years",
       y = "Probability of Overall Survival") +
  ggtitle("Evidence_C") +
  scale_color_manual(
    name = "Post-CGP treatment policy",
    values = c(
      "BSC" = "gray60",
      "Chemotherapy" = ggColorHue(6)[3],
      "Clinical_trial" = ggColorHue(6)[1],
      "Other_off_label" = ggColorHue(6)[5]
    )) +
  cowplot::theme_cowplot()
print(fig)

# Evidence D
tmp_data <- merged_data %>% 
  filter(Highest_evidence_level2 == "Evidence_D")

count <- survdiff(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data)
print(count)
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = tmp_data))
print(stat)
stat$coefficients

fig <- ggsurvfit(survfit2(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data), size = 1.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 4),
                  ylim = c(0, 1)) +
  labs(x = "Years",
       y = "Probability of Overall Survival") +
  ggtitle("Evidence_D") +
  scale_color_manual(
    name = "Post-CGP treatment policy",
    values = c(
      "BSC" = "gray60",
      "Chemotherapy" = ggColorHue(6)[3],
      "Clinical_trial" = ggColorHue(6)[1],
      "Other_off_label" = ggColorHue(6)[5]
    )) +
  cowplot::theme_cowplot()
print(fig)

# Evidence E
tmp_data <- merged_data %>% 
  filter(Highest_evidence_level2 == "Evidence_E")

count <- survdiff(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data)
print(count)
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = tmp_data))
print(stat)
stat$coefficients

fig <- ggsurvfit(survfit2(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data), size = 1.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 4),
                  ylim = c(0, 1)) +
  labs(x = "Years",
       y = "Probability of Overall Survival") +
  ggtitle("Evidence_E") +
  scale_color_manual(
    name = "Post-CGP treatment policy",
    values = c(
      "BSC" = "gray60",
      "Chemotherapy" = ggColorHue(6)[3],
      "Clinical_trial" = ggColorHue(6)[1],
      "Other_off_label" = ggColorHue(6)[5]
    )) +
  cowplot::theme_cowplot()
print(fig)

# No Evidence
tmp_data <- merged_data %>% 
  filter(Highest_evidence_level2 == "No_evidence")

count <- survdiff(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data)
print(count)
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = tmp_data))
print(stat)
stat$coefficients

fig <- ggsurvfit(survfit2(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data), size = 1.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 4),
                  ylim = c(0, 1)) +
  labs(x = "Years",
       y = "Probability of Overall Survival") +
  ggtitle("No_Evidence") +
  scale_color_manual(
    name = "Post-CGP treatment policy",
    values = c(
      "BSC" = "gray60",
      "Chemotherapy" = ggColorHue(6)[3],
      "Clinical_trial" = ggColorHue(6)[1],
      "Other_off_label" = ggColorHue(6)[5]
    )) +
  cowplot::theme_cowplot()
print(fig)
```

```{r each cancer type, warning=FALSE}
# Explicitly reorder the factor levels
merged_data$PostEP_treatment_policy_name_estimated_detail <- factor(
  merged_data$PostEP_treatment_policy_name_estimated_detail,
  levels = c("Chemotherapy", "BSC", "Clinical_trial", "Other_off_label")
)

for (tmp_cancer_type in wide_cancer_order) {
  tmp_data <- merged_data %>% filter(Oncotree_CODE_Final_wide == tmp_cancer_type)
  print(tmp_cancer_type)
  
  tmp <- tmp_data %>% 
    filter(!is.na(PostEP_treatment_policy_name_estimated_detail)) %>% 
    count(PostEP_treatment_policy_name_estimated_detail) %>% 
    nrow()
  if (tmp == 1){
    next()
  }
  
  count <- survdiff(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data)
  print(count)
  
  if (tmp_data %>% count(Sex_name) %>% nrow() == 1){
    stat <- summary(coxph(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail + Age_category, data = tmp_data))
  } else{
    stat <- summary(coxph(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = tmp_data))
  }
  print(stat)
  
  tmp_stat_df <- tibble(
    Oncotree_CODE_Final_wide = tmp_cancer_type,
    
    # Chemotherapy
    chemo_num = ifelse("PostEP_treatment_policy_name_estimated_detail=Chemotherapy" %in% names(count$n), count$n[["PostEP_treatment_policy_name_estimated_detail=Chemotherapy"]], 0),
    
    # Cliical trial
    clinical_trial_num = ifelse("PostEP_treatment_policy_name_estimated_detail=Clinical_trial" %in% names(count$n), count$n[["PostEP_treatment_policy_name_estimated_detail=Clinical_trial"]], 0),
    clinical_trial_hazard_ratio = ifelse("PostEP_treatment_policy_name_estimated_detailClinical_trial" %in% rownames(stat$conf.int), stat$conf.int["PostEP_treatment_policy_name_estimated_detailClinical_trial", "exp(coef)"], NA),
    clinical_trial_lower95 = ifelse("PostEP_treatment_policy_name_estimated_detailClinical_trial" %in% rownames(stat$conf.int), stat$conf.int["PostEP_treatment_policy_name_estimated_detailClinical_trial", "lower .95"], NA),
    clinical_trial_higher95 = ifelse("PostEP_treatment_policy_name_estimated_detailClinical_trial" %in% rownames(stat$conf.int), stat$conf.int["PostEP_treatment_policy_name_estimated_detailClinical_trial", "upper .95"], NA),
    clinical_trial_wald_p = ifelse("PostEP_treatment_policy_name_estimated_detailClinical_trial" %in% rownames(stat$coefficients), stat$coefficients["PostEP_treatment_policy_name_estimated_detailClinical_trial", "Pr(>|z|)"], NA),
    
    # Other off label
    other_off_label_num = ifelse("PostEP_treatment_policy_name_estimated_detail=Other_off_label" %in% names(count$n), count$n[["PostEP_treatment_policy_name_estimated_detail=Other_off_label"]], 0),
    other_off_label_hazard_ratio = ifelse("PostEP_treatment_policy_name_estimated_detailOther_off_label" %in% rownames(stat$conf.int), stat$conf.int["PostEP_treatment_policy_name_estimated_detailOther_off_label", "exp(coef)"], NA),
    other_off_label_lower95 = ifelse("PostEP_treatment_policy_name_estimated_detailOther_off_label" %in% rownames(stat$conf.int), stat$conf.int["PostEP_treatment_policy_name_estimated_detailOther_off_label", "lower .95"], NA),
    other_off_label_higher95 = ifelse("PostEP_treatment_policy_name_estimated_detailOther_off_label" %in% rownames(stat$conf.int), stat$conf.int["PostEP_treatment_policy_name_estimated_detailOther_off_label", "upper .95"], NA),
    other_off_label_wald_p = ifelse("PostEP_treatment_policy_name_estimated_detailOther_off_label" %in% rownames(stat$coefficients), stat$coefficients["PostEP_treatment_policy_name_estimated_detailOther_off_label", "Pr(>|z|)"], NA),
    
    # BSC
    BSC_num = ifelse("PostEP_treatment_policy_name_estimated_detail=BSC" %in% names(count$n), count$n[["PostEP_treatment_policy_name_estimated_detail=BSC"]], 0),
    BSC_hazard_ratio = ifelse("PostEP_treatment_policy_name_estimated_detailBSC" %in% rownames(stat$conf.int), stat$conf.int["PostEP_treatment_policy_name_estimated_detailBSC", "exp(coef)"], NA),
    BSC_lower95 = ifelse("PostEP_treatment_policy_name_estimated_detailBSC" %in% rownames(stat$conf.int), stat$conf.int["PostEP_treatment_policy_name_estimated_detailBSC", "lower .95"], NA),
    BSC_higher95 = ifelse("PostEP_treatment_policy_name_estimated_detailBSC" %in% rownames(stat$conf.int), stat$conf.int["PostEP_treatment_policy_name_estimated_detailBSC", "upper .95"], NA),
    BSC_wald_p = ifelse("PostEP_treatment_policy_name_estimated_detailBSC" %in% rownames(stat$coefficients), stat$coefficients["PostEP_treatment_policy_name_estimated_detailBSC", "Pr(>|z|)"], NA)
  )
  stat_df <- bind_rows(stat_df, tmp_stat_df)
    
  fig <- ggsurvfit(survfit2(Surv(OS_time_from_CGP, OS) ~ PostEP_treatment_policy_name_estimated_detail, data = tmp_data), size = 1.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 2),
                  ylim = c(0, 1)) +
  labs(x = "Years",
       y = "Probability of Overall Survival") +
  ggtitle(tmp_cancer_type) + 
  scale_color_manual(
    name = "Post-CGP treatment policy",
    values = c(
      "BSC" = "gray60",
      "Chemotherapy" = ggColorHue(6)[3],
      "Clinical_trial" = ggColorHue(6)[1],
      "Other_off_label" = ggColorHue(6)[5]
    )) +
  cowplot::theme_cowplot()
  
  print(fig)
}

stat_df
```

```{r stat, warning=FALSE}
merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Chemotherapy", "BSC", "Clinical_trial", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("BSC", "Chemotherapy", "Clinical_trial", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Clinical_trial", "BSC", "Chemotherapy", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Other_off_label", "Clinical_trial", "BSC", "Chemotherapy")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category, data = merged_data))
stat$coefficients[,5]
```

```{r stat2, warning=FALSE}
merged_data <- merged_data %>% 
  mutate(PS_category = case_when(PS %in% c(0,1) ~ "0-1",
                                 PS %in% c(2,3,4) ~ "2-",
                                 TRUE ~ NA_character_)) %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Chemotherapy", "BSC", "Clinical_trial", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("BSC", "Chemotherapy", "Clinical_trial", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Clinical_trial", "BSC", "Chemotherapy", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Other_off_label", "Clinical_trial", "BSC", "Chemotherapy")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category, data = merged_data))
stat$coefficients[,5]
```

```{r stat3, warning=FALSE}
merged_data <- merged_data %>%
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Chemotherapy", "BSC", "Clinical_trial", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category + Double_cancer_name, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("BSC", "Chemotherapy", "Clinical_trial", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category + Double_cancer_name, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Clinical_trial", "BSC", "Chemotherapy", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category + Double_cancer_name, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Other_off_label", "Clinical_trial", "BSC", "Chemotherapy")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category + Double_cancer_name, data = merged_data))
stat$coefficients[,5]
```

```{r stat4, warning=FALSE}
merged_data <- merged_data %>%
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Chemotherapy", "BSC", "Clinical_trial", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category + Double_cancer_name + Category, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("BSC", "Chemotherapy", "Clinical_trial", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category + Double_cancer_name + Category, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Clinical_trial", "BSC", "Chemotherapy", "Other_off_label")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category + Double_cancer_name + Category, data = merged_data))
stat$coefficients[,5]

merged_data <- merged_data %>% 
  mutate(PostEP_treatment_policy_name_estimated_detail = factor(PostEP_treatment_policy_name_estimated_detail, 
                                                                levels = c("Other_off_label", "Clinical_trial", "BSC", "Chemotherapy")))
stat <- summary(coxph(Surv(OS_time_from_CGP, OS)~ PostEP_treatment_policy_name_estimated_detail + Sex_name + Age_category + PS_category + Double_cancer_name + Category, data = merged_data))
stat$coefficients[,5]
```

```{r save, warning=FALSE}
stat_df %>% 
  write_csv("result/table/analysis/overall_prognosis/OS_by_treatment_policy_multivariate.csv")

stat_df %>% 
  filter(chemo_num >= 10 & clinical_trial_num >= 10) %>% 
  mutate(sig = if_else(clinical_trial_wald_p < 0.05, "p < 0.05", "p >= 0.05")) %>%
  mutate(Oncotree_CODE_Final_wide = factor(Oncotree_CODE_Final_wide, levels = c(wide_cancer_order, "PanCan"))) %>% 
  ggplot() +
  geom_point(aes(x = Oncotree_CODE_Final_wide, y = log2(clinical_trial_hazard_ratio), color = sig), size = 3) +
  geom_errorbar(aes(x = Oncotree_CODE_Final_wide, ymin = log2(clinical_trial_lower95), ymax = log2(clinical_trial_higher95)), width = 0.2) +
  geom_text(aes(x = Oncotree_CODE_Final_wide, y = 3.35, label = str_c("(", clinical_trial_num, ")")), size = 2) +
  geom_text(aes(x = Oncotree_CODE_Final_wide, y = -3.35, label = str_c("(", chemo_num, ")")), size = 2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(x = "Cancer Type", y = "log10(Hazard Ratio)") +
  theme_minimal() +
  coord_cartesian(ylim = c(-3.5, 3.5)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.title.x = element_blank()) +
  scale_color_manual(values = c("p < 0.05" = "red", 
                                "p >= 0.05" = "black")) +
  ggtitle("Clinical trial vs Insurance-approved therapy") +
  theme(legend.position = "none")
ggsave("result/pdf/analysis/overall_prognosis/Prognosis_clinical_trial_vs_insurance_multivariate.pdf")

stat_df %>% 
  filter(chemo_num >= 10 & other_off_label_num >= 10) %>%
  mutate(sig = if_else(other_off_label_wald_p < 0.05, "p < 0.05", "p >= 0.05")) %>%
  mutate(Oncotree_CODE_Final_wide = factor(Oncotree_CODE_Final_wide, levels = c(wide_cancer_order, "PanCan"))) %>%
  ggplot() +
  geom_point(aes(x = Oncotree_CODE_Final_wide, y = log2(other_off_label_hazard_ratio), color = sig), size = 3) +
  geom_errorbar(aes(x = Oncotree_CODE_Final_wide, ymin = log2(other_off_label_lower95), ymax = log2(other_off_label_higher95)), width = 0.2) +
  geom_text(aes(x = Oncotree_CODE_Final_wide, y = 3.35, label = str_c("(", other_off_label_num, ")")), size = 2) +
  geom_text(aes(x = Oncotree_CODE_Final_wide, y = -3.35, label = str_c("(", chemo_num, ")")), size = 2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(x = "Cancer Type", y = "log10(Hazard Ratio)") +
  theme_minimal() +
  coord_cartesian(ylim = c(-3.5, 3.5)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.title.x = element_blank()) +
  scale_color_manual(values = c("p < 0.05" = "red", 
                                "p >= 0.05" = "black")) +
  ggtitle("Off-label therapy vs Insurance-approved therapy") +
  theme(legend.position = "none")
ggsave("result/pdf/analysis/overall_prognosis/Prognosis_off_label_vs_insurance_multivariate.pdf")
```

```{r sessioninfo}
sessionInfo()
```
